### PR TITLE
feat: capacitor 5 support

### LINKED ISSUE #10: Capacitor 5
Are you going to update the plugin to support Capacitor 5? Capacitor 5 should be released soon.

https://capacitorjs.com/docs/next/updating/plugins/5-0

### PR DESCRIPTION
**Pull request by AE1NS**
Closes https://github.com/aparajita/capacitor-dark-mode/issues/10

### CODE REVIEW

**Comment by aparajita** [comment]
I'm under pressure to get a project done, I won't be able to release a capacitor 5 version for a few weeks.

**Comment by AndreyYolkin** [comment]
@AE1NS I published your PR as temporary solution under own scope: https://www.npmjs.com/package/@yolkin/capacitor-dark-mode 
Will deprecate after this PR closes

**Comment by aparajita** [comment]
@AndreyYolkin Thank you!

**Comment by aparajita** [comment]
Just released new version with Capacitor 5 support.

**Pull request closed without merging**
